scripts/f2py-f90wrap, setup.py
Hello,
On some distributions, the installed numpy release is in the form of '1.7.1rc1', which breaks a test on the triplet of numeric values after splitting and converting the numpy.__version__
I suggest to limit the test on major and minor only, and to start at 1.3 as it is the first documented release of numpy and is already 6 years old anyway.
Cheers
=> test on numpy release

examples/example-arrays/library.f90, examples/example-arrays/tests.py, examples/example-derivedtypes/Makefile, examples/example-derivedtypes/README.md, examples/example-derivedtypes/datatypes.f90, examples/example-derivedtypes/kind_map, examples/example-derivedtypes/library.f90, examples/example-derivedtypes/memory_profile.py, examples/example-derivedtypes/parameters.f90, examples/example-derivedtypes/tests.py
I've been working on another derived type example, that also includes arrays. It also contains pointer/allocatable arrays as arguments to illustrate it is not supported by f90wrap. Since I am only Fortran beginner, it think it would be good if this example could be reviewed. The example comes with a series of tests.
There's one thing I can not figure out why is not working as I think it should: on line [8](https://github.com/jameskermode/f90wrap/compare/master...davidovitch:example-dertype?expand=1#diff-56998375962074e7a89e68fbf1448a60R8) of ```datatypes.f90``` I define a derived type that includes two allocatable arrays in one module. If I try to do exactly the same on line [102](https://github.com/jameskermode/f90wrap/compare/master...davidovitch:example-dertype?expand=1#diff-56998375962 …
=> added an extended derived type example, including allocatable arrays

examples/cylinder/DNAD.f90, examples/cylinder/cylinder.ipynb
James,
Here are a couple of small items for the cylinder example
- Added a Jupyter notebook for a demo of how to use 'cyldnad.f90' in python.
- Also fixed parameter in DNAD.f90 so that it would treat 2 input variables (instead of 3).
James
=> Example notebook added

examples/example-strings/Makefile, examples/example-strings/README.md, examples/example-strings/kind_map, examples/example-strings/string_io.f90, examples/example-strings/tests.py
A simple example showing how to pass strings/characters. For the record, a too convoluted approach was used in PR #28 (with strings being converted to ascii integers and back). The method shown here is, hopefully, clean and simple.
There are two small things though:
* When importing from ```ExampleStrings_pkg``` the test ```test_set_global_string()``` fails (too many input arguments). When importing from ```ExampleStrings``` it works fine.
* There's something I am not sure about regarding the length of the strings that come back from Fortran, they are longer then I expect. Is there something obvious I am missing?
=> added simple example for passing along strings/characters

README.md
Fix typo in README thanks to #36
=> fix typo in README: `f90wrap_abort`

examples/Makefile, examples/arrays_fixed/Makefile, examples/arrays_fixed/README.md, examples/arrays_fixed/kind_map, examples/arrays_fixed/library.f, examples/arrays_fixed/memory_profile.py, examples/arrays_fixed/parameters.f, examples/arrays_fixed/tests.py, f90wrap/parser.py
I've used f90wrap on a large f90 code written with fixed formatting and had to tweak a few things in `parser.py`to get it to work:
* end of programs/routines/functions etc allowed to end with just `end`
* fixed form continuation lines are now handled in the `next` function
This PR does not cover all differences between fixed and free formatting, for example, comments are not caught in `next`. I tried using `regex` with `re.compile('^[^0-9\s]|^\s*!|^c|^C|^\\*')` instead of `find('!')`, but didn't succeed so far. But not catching comments doesn't seem to break anything.
Besides our own code, I've only run f90wrap on the tests which all pass, but please try it on more codes before merging to make sure I didn't screw anything up!
=> minor changes to parser for fixed formatting code

f90wrap/f90wrapgen.py, f90wrap/fortran.py, f90wrap/parser.py, f90wrap/transform.py, scripts/f90wrap
- Also a bug fix for the --only option (added __hash()__ function to module class)
- Also added --default-to-inout option to declare all arguments without intent to inout
The arrays of types are handled by creating a super-type containing the fixed size array, as suggested previously. So, type containers (super-types) are created each time an argument is type of one fixed size dimension. The already available routines then create constructors and destructors, making the container usable in python and the call line for the routine is slightly updated.
However, the result is quite cumbersome and very unlikely to be extendable to assumed shape arrays with dimension(:).
I also have written a minimal test example, but do not know how to add a folder to the repository...
=> Inelegant handling of one fixed dimension arrays of types as arguments 

f90wrap/f90wrapgen.py
Applying f90wrap to this little test module
```fortran
module linked_list
type :: link
type(link), pointer :: next => null()
end type link
end module
```
was leading to this generated code (just one s/r for brevity)
```fortran
subroutine f90wrap_link__get__next(this, f90wrap_next)
use linked_list, only: link
implicit none
type link_ptr_type
type(link), pointer :: p => NULL()
end type link_ptr_type
type link_ptr_type
type(link), pointer :: p => NULL()
end type link_ptr_type
integer, intent(in)   :: this(2)
type(link_ptr_type) :: this_ptr
integer, intent(out) :: f90wrap_next(2)
type(link_ptr_type) :: next_ptr
this_ptr = transfer(this, this_ptr)
next_ptr%p => this_ptr%p%next
f90wrap_next = transfer(next_ptr,f90wrap_next)
end subroutine f90wrap_link__get__next
```
in which the the `type …
=> Fixes repeated interfaces for linked-list construct

f90wrap/fortran.py, f90wrap/parser.py
A workground for the issue [#65 ](https://github.com/jameskermode/f90wrap/issues/65).
The Name argument in bind attribute is discarded right now. So extra works are needed to make it versatile.
This PR also fixed the bug about numpy dtype. 'string' is not a valid numpy dtype, it should be replaced by 'str'.
=> iso_c_binding support and numpy dtype bug fixed

examples/subroutine_args/Makefile, examples/subroutine_args/kind_map, examples/subroutine_args/subroutine_mod.f90, examples/subroutine_args/tests.py, f90wrap/parser.py
Fortran's line continuation can be interleaved with comments, often used in legacy applications to annotate groupings of dummy arguments. While the `f90wrap.parser` generally seems to handle comments between continued lines, subtle bugs can cause erroneous dummy argument lists. This PR fixes these subtle bugs and adds tests with multi-line dummy argument lists interrupted by comments.
Note: I've tried to emulate existing test setups, but please let me know if there are particular style changes required to bring the new tests in line with the existing codebase.
=> Bugfix and tests for comments interleaved in dummy argument lists

examples/derivedtypes/library.f90, examples/derivedtypes/tests.py, f90wrap/transform.py
This PR enables the creation and modification of derived types that contain array pointers and fixes the according tests (they exist, but had been disabled). The creation test was bugged in itself, since it associated the pointer with an array local to the subroutine, which becomes undefined (and possibly unallocated) once the program leaves that subroutine scope, as explained [here](https://stackoverflow.com/questions/11837616/fortran-allocatable-array-lifetime).
In general, array pointers like`real, pointer :: var` in derived types seem to work just like allocatable arrays (eg. `real, allocatable :: var` (can be passed around opaquely, but need to be allocated by custom Forrtan code). This means the restriction to skip them in `transform.py` can be lifted.
=> Array pointers in derived types

README.md
The "link.aip.org" link errors. I replaced it by the DOI link.
=> Fix link for Pletzer2008

f90wrap/pywrapgen.py, scripts/f90wrap
The issue was that when `class_names` was used, mapping of module and class names in the Python wrapper script was not consistent: some names remained by default.
Also, derived type name mapping was not functioning at all. Hence an additional `if`-line in the `f90wrap` script.
=> Small fix of `class_names` mapping

scripts/f2py-f90wrap
Candidate fix for #73 and #96 generated _module.c code not compiling on Windows10.
=> adjust C module code generation for Windows with mingw 

examples/callback_print_function_issue93/Makefile, examples/callback_print_function_issue93/README.md, examples/callback_print_function_issue93/callback_print_output_python.ipynb, examples/callback_print_function_issue93/caller.f90, examples/callback_print_function_issue93/cback.f90, examples/callback_print_function_issue93/kind_map, examples/callback_print_function_issue93/tests.py
Following report of issue #93 I've found a workaround I thought was worth documenting. The example is so far as I know not specific to f90wrap compared to f2py but may evolve to be. At any rate I hope this is useful for a pretty common task (capturing messages to print to a jupyter notebook)
=>  Add example setting up a python callback function 

examples/Makefile, examples/subroutine_contains_issue101/Makefile, examples/subroutine_contains_issue101/run.py, examples/subroutine_contains_issue101/test.f90, f90wrap/parser.py
This is an attempt to fix #101.
I have no clue how robust it is, for the simple example in the issue it produces the desired result (i.e., only yields the outer subroutine but none of the inner subroutines or functions) in the Python module. Small variations (e.g., exchange order of function/subroutine) produced the same result.
Please have a look and let me know what you think!
=> Skip over subroutines and functions that are contained in a subroutines

README.md, examples/cylinder/kind_map, examples/subroutine_contains_issue101/Makefile, f90wrap/__init__.py, f90wrap/parser.py
The line
prototype = re.compile(r'^module procedure ([a-zA-Z0-9_,\s]*)')
in parser.py did not include re.IGNORECASE so 'module procedure' had to be written in lower case in order for interfaces to work.
For example:
INTERFACE sort
MODULE PROCEDURE sort_sp, sort_dp
end interface sort
did not work.
INTERFACE sort
module procedure sort_sp, sort_dp
end interface sort
worked.
There are four other lines fdoc_*, that deal with the documentation, that do also not ignore the case. I do not know if this is wanted or not. I am still using doxygen to document my Fortran code.
Kind regards
Matthias
=> 'module procedure' was parsed without ignoring the case

examples/arrayderivedtypes/test.f90, f90wrap/pywrapgen.py
Fix typo when generating the python class for derived arrays.
=> fix wrapping array of derived types

scripts/f2py-f90wrap
I got a segmentation fault when using f90wrap_abort subroutine. The message length was to big, I suggest this fix to prevent this probleme.
The other commit Closes #110, the backslash need to be escaped in the python string.
=> f90wrap_abort message

examples/recursive_type_array/Makefile, examples/recursive_type_array/kind_map, examples/recursive_type_array/test.f90, examples/recursive_type_array/tests.py, f90wrap/f90wrapgen.py
Using recursion within derived types was previously address in #74, but that fix only allows for scalar recursive definitions. Defining a recursive array such as:
```
type t_node
type(t_node),dimension(:),allocatable :: node
end type t_node
```
was not allowed and results in the errors such as:
```
f90wrap_test.f90:11:24:
11 |     type t_node_ptr_type
|                        1
Error: Derived type definition of 't_node_ptr_type' at (1) has already been defined
f90wrap_test.f90:13:7:
13 |     end type t_node_ptr_type
|       1
Error: Expecting END SUBROUTINE statement at (1)
```
This is due to the pointers to the parent and child nodes being named the same thing within the f90wrap generated Fortran code.
Adding a check for the recursive derived type (such as in #74):
```
same_type = …
```
=> Fix for recursive type array

f90wrap/fortrantype.py, f90wrap/pywrapgen.py
This fix should address libAtoms/QUIP#235 by transferring ownership of derived type objects allocated in Fortran back to Python for subroutines with `intent(out)` arguments of a derived type.
=> proposed fix for QUIP issue 235

.gitignore, examples/CMakeLists.txt, f90wrap/f90wrapgen.py, f90wrap/fortran.py, f90wrap/latex.py, f90wrap/parser.py, f90wrap/pywrapgen.py, f90wrap/transform.py, scripts/f90wrap, test/.gitignore, test/__init__.py, test/samples/circle.f90, test/samples/test_circle.f90, test/test_parser.py, test/test_transform.py
Hello and Happy Thanksgiving! 
I am planning to wrap a Fortran codebase, some of which uses object-oriented style with type-bound procedures. I see that is not yet supported in f90wrap (per #37), but the bones look good, so I've started the work to add basic support for (non-polymorphic) object oriented Fortran. This pull request is a work-in-progress to solicit feed back on the design so far. 
The major changes to the code are as follows:
1. The parser now reads the `contains` section of a derived type.
2. There is now a `Binding` node type which represents "regular", "generic", or "final" type-bound procedures. Like Interfaces, each Binding is initially populated with one (or more, in the case of a generic binding) Prototypes to represent which module procedures are associated with a …
=> Issue37 Part 1: Type procedure parsing

f90wrap/fortran.py, f90wrap/parser.py
Fixes regression introduced in PR #133, and fixes issue libAtoms/quip#264
=> Collapse repeated interface blocks after parsing

scripts/f2py-f90wrap
Modified `f2py-f90wrap` to make f2py rule replacement more general. Avoiding use of `\t` tab character as it appears to be interpreted differently with Big Sur.
This is a fix for Issue #135.
=> Update for compatibility issues on Mac

f90wrap/f90wrapgen.py
Due to the f2py still not work well for character array definition (https://github.com/numpy/numpy/issues/18684), so change the character array definition to F77-style.
=> character array to F77 style

scripts/f90wrap, setup.py
- added `--f90-mod-name` command line augment
- reduce required numpy version to 1.13 for consistency with `oldest-supported-numpy`
=> fixes to f90wrap to build latest QUIP

examples/errorbinding/Makefile, examples/errorbinding/README.md, examples/errorbinding/datatypes.f90, examples/errorbinding/kind_map, examples/errorbinding/parameters.f90, f90wrap/parser.py
Using f90wrap in [this project](https://gitlab.com/enrico_facca/geometry) I noticed that in the parser script the class Binding was not imported. Including this class fixed my issues.
In order to reproduce the error follow the instruction in the README file and create the fortran-python interface with 
```
make f2py_interface_geometry
```
=> import Binding class included in parser

examples/default_i8/Makefile, examples/default_i8/kind_map, examples/default_i8/test.f90, examples/default_i8/tests.py, f90wrap/f90wrapgen.py
Fixes issue 164.
Arrays in derived types with 2 or more dimensions were before not accessible in python if the Fortran sources where compiled with integer(8) as default integer because these settings broke the f90-C interfaces generated by f90wrap.
This is now avoided by using for integer types from the iso_c_binding module in the generated Fortran routines.
=> Improved compatibility with integer(8) as default integer in F90 sources

examples/CMakeLists.txt, examples/Makefile, examples/class_names/Makefile, examples/class_names/class_names.json, examples/class_names/kind_map, examples/class_names/test.f90, examples/class_names/tests.py, f90wrap/pywrapgen.py
The issue seems to boil down to line 729 of `pywrapgen.py` (construction of a dict of function arguments) which refers to `cls_mod_name.title()`. The proper way of transforming module class name is a  function `normalise_class_name()`.
Closes #172
=> Fix issue 172

f90wrap/f90wrapgen.py, f90wrap/pywrapgen.py, f90wrap/transform.py
Fortran 2003 allows suubroutines names with max 63 characters. This is to make sure f90wrap generated subroutines are not to long
=> Handle long fortran subroutine names

README.md, examples/Makefile, examples/type_check/Makefile, examples/type_check/main.f90, examples/type_check/type_check_test.py, f90wrap/pywrapgen.py, f90wrap/scripts/main.py
This pull request addresses two current limitations:
- As derived type are accessed via an integer representing the instance address, all derived type are the same type from the wrapper point of view. Polymorphism with derived type is not possible.
- Arrays with non corresponding type/shape to the underlying Fortran subroutines are sometimes passed without raising a TypeError (I guess automatique conversion from f2py). Polymorphism with different numpy array dtype or shape is not always possible: issue #107 
This pr adds type and shape checks in the python wrapper function. It raises TypeError if the type/shape provided to the python function does not match the type/shape of the wrapped Fortran subroutine.
It allows better support for Fortran interfaces. For instance, it enables one to …
=> Type check for better fortran interface support

examples/arrays/library.f90, examples/arrays/tests.py, f90wrap/pywrapgen.py
In `sub_array_*` functions, the global variable has the same name as the input local variable, and sometimes it doesn't work as expected. The global variable is replaced by `globals()`. 
Environment:
- python: 3.10.6
- ubuntu: 22.04
=> Change global variable name in set_array_

examples/Makefile, examples/derivedtypes_procedure/Makefile, examples/derivedtypes_procedure/library.f90, examples/derivedtypes_procedure/tests.py, f90wrap/f90wrapgen.py, f90wrap/pywrapgen.py, f90wrap/transform.py
Improve and update the support for type-bound procedures, allowing for multiple types of procedures. Additionally, module procedures also can be used as regular procedures.
=> support type-bound procedures

examples/derivedtypes/tests.py, f90wrap/fortrantype.py
Add `copy` to class `FortranDerivedType` and `FortranDerivedTypeArray`. The copy will only keep the values and disconnect to the Fortran code. The copy of `FortranDerivedTypeArray` will return a list of copied `FortranDerivedType`.
=> add copy to FortranDerivedType

.github/workflows/build-wheels.yml
Go back to windows-2019 rather than windows-latest, since -latest now links to windows-server-2022, which breaks the wheel building in CI.
Example failure: 
https://github.com/jameskermode/f90wrap/actions/runs/4939251190/jobs/8829813446#step:4:185
=> Revert windows runner change

examples/arrays/Makefile, examples/arrays/tests.py, f90wrap/pywrapgen.py, f90wrap/scripts/main.py
Add `--relative` to f90wrap to change the absolute import to the relative import in the package. This can be used to create many sub-packages in one big package.
=> support relative import for the package

examples/optional_string/Makefile, examples/optional_string/main.f90, examples/optional_string/test.py, f90wrap/scripts/f2py_f90wrap.py
Calling a wrapped routine with an optional string array produces a segfault with numpy version >= 1.24.0 when called without the argument.
I belive the problems is that the C generated code trys to acces data from Py_None object.
This PR adds a check in the C generated code from f2py_f90wrap.py script.
It also add some related tests on various way to manipulate strings.
=> Optional out string

examples/Makefile, examples/optional_string/test.py, pyproject.toml
Sorry, I forgot to add the string tests to the examples makefile. Completes #209
**Edit:** Tests actually needs the `packaging` package to skip tests that are known to fail with older versions of numpy. Is this a problem?
=> Run optional_string tests from examples Makefile

examples/derivedtypes_procedure/library.f90, f90wrap/parser.py
More than one variable after `public` or `private` but without a double colon.
=> Missing colon in public and private

examples/subroutine_contains_issue101/test.f90, f90wrap/parser.py
Similar to #134, but multi-functions are contained in a function.
=> Multi-functions are contained in a function

.github/workflows/build-wheels.yml
Using the new GitHub Actions Macos runner `macos-14` to build the `macosx-arm64` wheels.
=> Use macos-14 to support arm64

examples/arrays/Makefile, examples/arrays/parameters.f90, f90wrap/f90wrapgen.py, f90wrap/pywrapgen.py
The same subroutine names in different modules or one is a regular subroutine, and others in modules.
=> fix same subroutine names in different modules

examples/Makefile, examples/long_subroutine_name/Makefile, examples/long_subroutine_name/Makefile.meson, examples/long_subroutine_name/main.f90, examples/long_subroutine_name/test.py, f90wrap/f90wrapgen.py, f90wrap/pywrapgen.py
Since PR #215, the name of the module is included in the name of subroutines. As a result, the character limit for a subroutine name is quickly reached. Taking a look at the pull requests, I realised that this problem had already been encountered and solved with the `shorten_long_name` function (PR #178). I took the liberty of applying the same correction to the subroutine names.
When I added the tests, I also realised that this fix was missing for scalar setter.
=> FIX: Long subroutine name

.github/workflows/python-package.yml, README.md, examples/optional_string/test.py, f90wrap/scripts/f2py_f90wrap.py, pyproject.toml
Hello,
A pull request to support numpy 2.0
[numpy-2-0-python-api-removals](https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-python-api-removals)
- Alias ``np.string_`` has been removed. Use ``np.bytes_`` instead.
- Alias ``np.unicode_`` has been removed. Use ``np.str_`` instead.
[numpy-2-0-c-api-removals](https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-c-api-removals)
- ``npy_interrupt.h`` and the corresponding macros like ``NPY_SIGINT_ON`` have been removed.
Need to include ``<signal.h>`` to  avoid ``error: 'SIGINT' undeclared (first use in this function)``
I am not sure if the ``python-package.yml`` workflow is still useful since the same tests are run inside ``build-wheels.yml``
=> MAINT: numpy 2.0 support

examples/issue227_allocatable/Makefile, examples/issue227_allocatable/Makefile.meson, examples/issue227_allocatable/alloc_output.f90, examples/issue227_allocatable/run.py, f90wrap/transform.py
This is the minimum change that allows function outputs of allocatable derived types. The rationale is explained in #227.
=> Fix #227: Allow allocatable derived types as function outputs

examples/CMakeLists.txt, examples/Makefile, examples/docstring/Makefile, examples/docstring/docstring_test.py, examples/docstring/main.f90, examples/intent_out_size/Makefile, examples/intent_out_size/Makefile.meson, examples/intent_out_size/main.f90, examples/intent_out_size/tests.py, examples/return_array/Makefile, examples/return_array/Makefile.meson, examples/return_array/main.f90, examples/return_array/test.py, f90wrap/f90wrapgen.py, f90wrap/fortran.py, f90wrap/parser.py, f90wrap/pywrapgen.py, f90wrap/transform.py
This PR sits on top of #230
Handle wrapping of function returning an array.
In the Python wrapper, add the shape of the array as arguments wrapped call
Otherwise it fails with an errors like: `TypeError: _pywrapper.f90wrap_m_test__return_array_size() missing required argument 'n1' (pos 1)`
=> Return array

examples/CMakeLists.txt, examples/Makefile, examples/docstring/Makefile, examples/docstring/docstring_test.py, examples/docstring/main.f90, examples/intent_out_size/Makefile, examples/intent_out_size/Makefile.meson, examples/intent_out_size/main.f90, examples/intent_out_size/tests.py, examples/optional_string/Makefile.meson, examples/optional_string/main.f90, examples/optional_string/test.py, examples/return_array/Makefile, examples/return_array/Makefile.meson, examples/return_array/main.f90, examples/return_array/test.py, examples/string_array_input_f2py/Makefile, examples/string_array_input_f2py/Makefile.meson, examples/string_array_input_f2py/main.f90, examples/string_array_input_f2py/tests.py, examples/type_check/Makefile, examples/type_check/kind.map, examples/type_check/main.f90, examples/type_check/type_check_test.py, f90wrap/f90wrapgen.py, f90wrap/fortran.py, f90wrap/parser.py, f90wrap/pywrapgen.py, f90wrap/transform.py
This PR sits on top of #230 and #231
Update the type check feature that checks the Python types that are passed to Fortran routines.
Improves #182:
- Support for optional arguments
- Better support for strings
- Better error messages when it fails
- Be less strict with scalar input:
When the wrapper is not wrapping a Fortran interface, use numpy `astype` member function to convert types to the right size. For instance, int32 to int64. This makes the Python wrapper interfaces more Pythonic.
When the wrapper is wrapping a Fortran interface, the behavior stays the same, strict type matching between Python input type and the Fortran signature is required so that the correct Fortran routine is called.
=> Type check

.github/workflows/build-wheels.yml, examples/fortran_oo/Makefile, examples/fortran_oo/Makefile.meson, examples/fortran_oo/main-oo.f90, examples/fortran_oo/oowrap_test.py, examples/optional_string/test.py, examples/output_kind/Makefile.meson, examples/remove_pointer_arg/tests.py, examples/return_array/Makefile.meson, examples/string_array_input_f2py/Makefile, examples/string_array_input_f2py/Makefile.meson, examples/string_array_input_f2py/tests_no_sign.py, examples/string_array_input_f2py/tests_sign.py, examples/type_check/Makefile.meson, pyproject.toml
This is a variant of #239 where I did some modifications on top of the great work of @danbeibei
1. Change from pytest back to unittest. Dependencies between tests are preserved as comments for later.
2. Change primary accuracy to real(kind=8) and pre-compute pi. I felt more confident with the "almost equal" asserts that work slightly differently in unittest.
3. Fix #242 due to small issues in `Makefile.meson` in some examples.
@jameskermode if this fits your requirements, it should be ready to merge -- ideally first #239 and than this one here.
=> Fortran oo support with unittest

.gitignore, examples/Makefile, examples/issue227_allocatable/run.py, examples/issue235_allocatable_classes/Makefile, examples/issue235_allocatable_classes/Makefile.meson, examples/issue235_allocatable_classes/myclass.f90, examples/issue235_allocatable_classes/myclass_factory.f90, examples/issue235_allocatable_classes/mytype.f90, examples/issue235_allocatable_classes/run.py, f90wrap/f90wrapgen.py, f90wrap/fortran.py, f90wrap/pywrapgen.py, f90wrap/transform.py
Fixes #235 . This PR sits on top of #230, #231, #232, #237, #238 and #239.
=> Fix #235 allocatable classes

f90wrap/pywrapgen.py
Follow the recommended way of using the logger in the generated Python modules (https://docs.python.org/3/library/logging.html) by creating a logger in each module: `logger = logging.getLogger(__name__)`. Otherwise, at runtime, it will interact with other modules' loggers.
=> Create logger for the module scope instead of using global logger

README.md, examples/CMakeLists.txt, examples/Makefile, examples/auto_raise_error/Makefile, examples/auto_raise_error/Makefile.meson, examples/auto_raise_error/main.f90, examples/auto_raise_error/tests.py, examples/issue235_allocatable_classes/Makefile, f90wrap/f90wrapgen.py, f90wrap/pywrapgen.py, f90wrap/scripts/main.py
Add a flag to automatically generate calls to the abort function in the f90wrap Fortran wrappers to raise Python RuntimeErrors.
To my knowledge, there is no standard way of handling errors in Fortran; this feature matches the way we handle errors in our code and might match the way others handle errors.
In our Fortran code, subroutines use one integer variable that holds the error code and one character variable that holds the error message. If the error code is different from 0, the program stops, and a call stack is built via the error character variable.
The flag allows specifying the variable names used in the wrapped code for error handling and generates a call to `f90wrap_abort` in the f90wrap Fortran wrappers, which is called if the error code is different from 0.
The added …
=> Auto error raise

examples/issue258_derived_type_attributes/Makefile, examples/issue258_derived_type_attributes/dta_cc.f90, examples/issue258_derived_type_attributes/dta_ct.f90, examples/issue258_derived_type_attributes/dta_tc.f90, examples/issue258_derived_type_attributes/dta_tt.f90, examples/issue258_derived_type_attributes/test.py, f90wrap/f90wrapgen.py
This PR fixes issue #258 by extending the generation of derived type getter functions with the additional `wrapper_type` layer which is also used for polymorphic derived types as return values.
Please let me know if anything needs to be changed or improved.
Thanks for the great package!
=> fix issue 258 - incorrect generation of getter functions for polymorphic derived types

f90wrap/parser.py
Some module variable have multiple declaration in different #ifdef scopes
Handle this by checking if module variable was allready parsed
=> Module variable

examples/optional_string/main.f90, examples/optional_string/test.py, f90wrap/pywrapgen.py
This fixes a bug in the type-checking feature that returned an error when character length was specified.
`TypeError: Expecting 'str' (code '2') with dim '-1' but got '|S6' (code '18') with dim '1'`
=> Fix handling of Fortran string arrays with explicit shape
